name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#       env:
#         checkout: actions/checkout@v3
#         RDS_PORT: 3306
#         RDS_HOSTNAME: aa11qm9tbbm33mc.ciyggvszmd6k.sa-east-1.rds.amazonaws.com
#         RDS_DB_NAME: aa11qm9tbbm33mc
#         RDS_USERNAME: admin
#         RDS_PASSWORD: 5FNPW#Xn5DEAP5W
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Set environment variables
#     - name: Sync Database
#       run: |
#         php artisan site:refresh
#         php artisan migrate
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: PlayTennis Backend
        environment_name: Playtennisbackend-env
        version_label: 1
        region: sa-east-1
        deployment_package: deploy.zip
        use_existing_version_if_available: true
