name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Deyployment:
  
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: PlayTennis Api
        environment_name: playtennisapi-env
        version_label: 1
        region: sa-east-1
        deployment_package: deploy.zip
        use_existing_version_if_available: true
    - name: Generate key
      run: |
        php artisan key:generate
        php artisan env:set DB_PORT=3306
        php artisan env:set DB_HOST=playtennisdb.ciyggvszmd6k.sa-east-1.rds.amazonaws.com
        php artisan env:set DB_DATABASE=playtennis
        php artisan env:set DB_USERNAME=playtennis
        php artisan env:set DB_PASSWORD=5FNPWhXn5DEAP5WOplV
    - name: Get env
      run: cat .env
    - name: Run migration
      run: |
           php artisan migrate
           php atisan site:refresh
