name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Deyployment:
  
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Install Dependencies
      run: composer install
    - name: Generate key and set env
      env: 
        DB_PASSWS: ${{ secrets.DB_PASSWORD }}
        MAIL_SECRET: ${{ secrets.MAIL_SECRET }}
        DB_HOST: ${{ secrets.DB_HOST}}
        DB_USER: ${{ secrets.DB_USER }}
      run: |
        php artisan key:generate
        php artisan env:set APP_DEBUG=false
        php artisan env:set APP_URL=hplaytennis.chlxztkd2ael.sa-east-1.rds.amazonaws.com
        
        php artisan env:set DB_PORT=3306
        php artisan env:set DB_HOST=$DB_HOST
        php artisan env:set DB_DATABASE=$DB_USER
        php artisan env:set DB_USERNAME=$DB_USER
        php artisan env:set DB_PASSWORD=$DB_PASSWS

        php artisan env:set MAIL_MAILER=smtp
        php artisan env:set MAIL_HOST=smtp-mail.outlook.com
        php artisan env:set MAIL_PORT=587
        php artisan env:set MAIL_USERNAME=souzavito@hotmail.com
        php artisan env:set MAIL_PASSWORD=$MAIL_SECRET
        php artisan env:set MAIL_ENCRYPTION=tls
        php artisan env:set MAIL_FROM_ADDRESS=souzavito@hotmail.com
        php artisan env:set MAIL_FROM_NAME=PlayTennis
        php artisan storage:link
        
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    - name: Get env
      run: cat .env
    - name: Run migration
      run: |
           php artisan migrate
           php artisan site:refresh
    - name: Deploy to EB 
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: playtennis
        environment_name: Playtennis-env
        version_label: 'alpha-1.0.1'
        region: sa-east-1
        deployment_package: deploy.zip
        use_existing_version_if_available: true
